// graphcontract.js - what the studio requires of any graph, in one place.
//
// It lives here rather than in tools/import_graph.js because that file is a CLI: it
// reads process.argv at the top level and exits, so importing it to read a constant
// runs the importer. The list is also the source of CONTRACT.md, generated by
// tools/build_contract.js, so prose and code cannot drift.
//
// Nothing here names a claim, a film or an entity. It is the SHAPE of a graph, and the
// studio is coupled to nothing else.

export const REQUIRED = {
  films: ['films'], claims: ['claims'], entities: ['entities'], locks: ['locks'],
  sheets: ['sheets'], memos: ['memos'], passages: ['passages'],
  source_register: ['sources'], kandas: ['kandas'], episodes: ['episodes'],
  material_world: [], typography: ['scripts'], grade: [], effects: ['shots'],
  transitions: ['joins'], narrator: ['languages'], music: [],
  evidence_libraries: ['libraries'], traditions: ['traditions'], spend: ['rows'],
};
export const OPTIONAL = ['threads', 'incidents', 'app_design'];

// Files the studio DOES read but does not require. They were warned about as unused
// for as long as it took someone to read render_policy.json and find that the identity
// method - "reference-conditioned; never text-only" - had been sitting there unread,
// warned about by this very list, while the renderer generated text-only.
export const READ_IF_PRESENT = ['render_policy', 'seed_policy', 'rights_policy', 'restricted_index'];
