# One unit = one meaning, on one shot, with one speaker, in every language.
# Sentence parity is NOT required. Factual, speaker and visual alignment IS.
# ("L", beat, en, hi, te, speaker)   ·   ("P", label, seconds)
D, V, VS = 'DASHARATHA', 'VISHVAMITRA', 'VASISHTHA'
U = {
'M1': [
 ('L',2,'A sage came to Ayodhyā.','अयोध्या में एक ऋषि आए।','అయోధ్యకు ఒక ఋషి వచ్చాడు.',None),
 ('P','pause',1.2),
 ('L',7,'He asked what the sage wanted.','उन्होंने पूछा — आपको क्या चाहिए?','మీకేం కావాలి అని అడిగాడు.',D),
 ('L',11,'And before the sage answered — he gave his word.','और ऋषि के कुछ कहने से पहले ही — वचन दे दिया।','ఋషి చెప్పకముందే — మాట ఇచ్చేశాడు.',None),
 ('P','pause',1.2),
 ('L',13,'Whatever it was.','जो भी हो।','ఏదైనా సరే.',None),
 ('P','two seconds',2.0),
 ('L',14,'The sage had not said it yet.','ऋषि ने अभी कहा ही नहीं था।','ఋషి ఇంకా చెప్పనే లేదు.',None)],
'M2': [
 ('L',1,'In the court of Ayodhyā, the sage sat before the king.','अयोध्या के दरबार में ऋषि विश्वामित्र राजा के सामने बैठे थे।','అయోధ్య సభలో విశ్వామిత్రుడు రాజు ముందు కూర్చున్నాడు.',None),
 ('L',2,'And Dasharatha had already given his word.','और दशरथ वचन दे चुके थे — ऋषि जो माँगेंगे, वो देंगे।','దశరథుడు అప్పటికే మాట ఇచ్చేశాడు — ఋషి ఏం అడిగినా ఇస్తానని.',None),
 ('L',3,'Before he asked, the sage told him: keep your word.','माँगने से पहले ऋषि ने कहा — अपना वचन निभाना।','అడిగే ముందే ఋషి అన్నాడు — మాట నిలబెట్టుకో.',V),
 ('P','pause',1.2),
 ('L',4,'Far from here, in the forest, Viśvāmitra had begun a yajña.','दूर, जंगल में, विश्वामित्र ने एक यज्ञ शुरू किया था।','ఇక్కడికి దూరంగా, అడవిలో, విశ్వామిత్రుడు ఒక యజ్ఞం మొదలుపెట్టాడు.',None),
 ('L',6,'Two rākṣasas kept breaking it. Mārīca. Subāhu.','दो राक्षस उसे बार-बार तोड़ देते थे। मारीच। सुबाहु।','ఇద్దరు రాక్షసులు దాన్ని పదే పదే పాడు చేసేవారు. మారీచుడు. సుబాహుడు.',None),
 ('L',8,'They poured flesh and blood over the altar.','वो वेदी पर माँस और ख़ून उँडेल देते थे।','వేదిక మీద మాంసం, రక్తం పోసేవారు.',None),
 ('P','pause',1.2),
 ('L',10,'He was under a vow. He couldn\'t curse them.','ऋषि व्रत में थे। शाप दे नहीं सकते थे।','ఆయన వ్రతంలో ఉన్నాడు. శాపం పెట్టలేడు.',None),
 ('L',12,'So he had come to the king.','इसलिए वो राजा के पास आए थे।','అందుకే రాజు దగ్గరికి వచ్చాడు.',None),
 ('P','pause',1.2),
 ('L',13,'Ten nights. That was all he asked.','दस रातें। बस इतना ही माँगा था।','పది రాత్రులు. అంతే అడిగాడు.',None),
 ('P','two seconds',2.0),
 ('L',15,'He did not ask for the army.','उन्होंने सेना नहीं माँगी।','సైన్యం అడగలేదు.',None),
 ('P','two seconds',2.0),
 ('L',17,'Rāma.','राम।','రాముడు.',None)],
'M3': [
 ('L',2,'Viśvāmitra had no doubt. With him there, Rāma would finish them.',
  'विश्वामित्र को कोई शक नहीं था — वो साथ रहें तो राम उन दोनों को ख़त्म कर देंगे।',
  'విశ్వామిత్రుడికి ఏ సందేహం లేదు — ఆయన తోడు ఉంటే రాముడు ఆ ఇద్దరినీ చంపేస్తాడు.',V),
 ('L',3,'He said: if Vasiṣṭha and the counsellors agreed, let Rāma go.','उन्होंने कहा — अगर वसिष्ठ और मंत्री मान जाएँ, तो राम को जाने दो।','వసిష్ఠుడూ, మంత్రులూ ఒప్పుకుంటే రాముణ్ణి పంపించు, అన్నాడు.',V),
 ('L',4,'Ten nights. That was all he asked.','दस रातें। बस इतना ही माँगा था।','పది రాత్రులు. అంతే అడిగాడు.',None),
 ('P','pause',1.2),
 ('L',7,'Dasharatha... had only fear. Not of Rāma. For him.','दशरथ को... सिर्फ़ डर था। राम पर नहीं। राम के लिए।','దశరథుడికి... భయం మాత్రమే. రాముడి మీద కాదు. రాముడి కోసం.',None),
 ('L',8,'He said Rāma was not yet sixteen.','उन्होंने कहा — राम अभी सोलह के भी नहीं थे।','రాముడికి ఇంకా పదహారు కూడా నిండలేదు, అన్నాడు.',D),
 ('L',9,'The way his father saw it, he hadn\'t finished learning weapons.','पिता की नज़र में, अभी उसने हथियार पूरे सीखे भी नहीं थे।','తండ్రి దృష్టిలో — ముక్కుపచ్చలారని పిల్లాడికి ఇంకా ఆయుధాలు పూర్తిగా రావు.',D),
 ('P','pause',1.2),
 ('L',11,'The king offered his army.','राजा ने अपनी सेना देने को कहा।','రాజు తన సైన్యాన్ని ఇస్తానన్నాడు.',None),
 ('L',14,'He said he\'d go himself, bow in hand, while he lived.','कहा — मैं ख़ुद चलूँगा। धनुष लेकर। जब तक साँस है।','నేనే వస్తాను అన్నాడు. విల్లు పట్టుకుని. ఊపిరి ఉన్నంతవరకు.',D),
 ('L',16,'Anything. Anything but Rāma.','कुछ भी। बस राम नहीं।','ఏదైనా. రాముడు తప్ప.',None),
 ('L',19,'He said he couldn\'t live without Rāma. Not for a moment.','उन्होंने कहा — राम के बिना वो एक पल नहीं रह सकते।','రాముడు లేకుండా ఒక్క క్షణం కూడా ఉండలేనని అన్నాడు.',D),
 ('P','two seconds',2.0),
 ('L',21,'He said no.','उन्होंने ना कह दिया।','ఆయన కాదన్నాడు.',D)],
'M4': [
 ('L',2,'The king asked who they were. Whose they were.','राजा ने पूछा — ये कौन हैं? किसके हैं?','రాజు అడిగాడు — వాళ్ళు ఎవరు? ఎవరి మనుషులు?',D),
 ('L',4,'Viśvāmitra answered slowly.','विश्वामित्र ने धीरे से जवाब दिया।','విశ్వామిత్రుడు నెమ్మదిగా చెప్పాడు.',None),
 ('L',5,'They don\'t come on their own, he said. Someone sets them on.','उन्होंने कहा — वो अपने आप नहीं आते। कोई उन्हें उकसाता है।','వాళ్ళంతట వాళ్ళు రారు, అన్నాడు. ఎవరో వాళ్ళని ఉసిగొలుపుతారు.',V),
 ('P','two seconds',2.0),
 ('L',8,'Rāvaṇa.','रावण।','రావణుడు.',None),
 ('L',9,'King of the rākṣasas. Brother of Kubera. He has a boon.','राक्षसों का राजा। कुबेर का भाई। उसे वरदान मिला हुआ है।','రాక్షసుల రాజు. కుబేరుడి తమ్ముడు. వాడికి వరం ఉంది.',None),
 ('L',12,'Dasharatha heard the name.','दशरथ ने नाम सुना।','దశరథుడు ఆ పేరు విన్నాడు.',None),
 ('P','pause',1.2),
 ('L',13,'He said he couldn\'t stand against Rāvaṇa, nor could his army.','उन्होंने कहा — रावण के सामने वो ख़ुद नहीं टिक सकते। न उनकी सेना।','రావణుడి ముందు తను నిలబడలేడు, తన సైన్యం కూడా — అన్నాడు.',D),
 ('L',16,'How, he asked, could a boy?','उन्होंने पूछा — तो एक बच्चा कैसे?','ఇంక ఒక పిల్లాడు ఎలా, అని అడిగాడు.',D),
 ('P','two seconds',2.0),
 ('L',17,'Once more... he said no.','एक बार फिर... उन्होंने ना कह दिया।','మళ్ళీ... ఆయన కాదన్నాడు.',D)],
'M5': [
 ('L',2,'Viśvāmitra hadn\'t moved through any of it.','विश्वामित्र अब तक चुपचाप बैठे थे।','విశ్వామిత్రుడు ఇప్పటిదాకా కదలలేదు.',None),
 ('P','pause',1.2),
 ('L',3,'Now he moved.','अब वो हिले।','ఇప్పుడు కదిలాడు.',None),
 ('P','two seconds',2.0),
 ('L',4,'He said —','उन्होंने कहा —','అన్నాడు —',None),
 ('L',8,'"You gave your word, Dasharatha."','"तुमने वचन दिया था, दशरथ।"','"మాట ఇచ్చావు, దశరథా."',V),
 ('P','pause',1.2),
 ('L',9,'"Now you want to take it back."','"अब उसे वापस लेना चाहते हो।"','"ఇప్పుడు వెనక్కి తీసుకోవాలని చూస్తున్నావు."',V),
 ('P','pause',1.2),
 ('L',10,'"That is not the way of the Raghus."','"रघुवंश में ऐसा नहीं होता।"','"రఘువంశంలో ఇలా జరగదు."',V),
 ('P','two seconds',2.0),
 ('L',12,'"If this is your decision... I will go."','"अगर यही तुम्हारा फ़ैसला है... तो मैं जाता हूँ।"','"ఇదే నీ నిర్ణయం అయితే... నేను వెళ్తాను."',V),
 ('L',13,'"The way I came."','"जैसे आया था।"','"వచ్చినట్టే."',V),
 ('P','pause',1.2),
 ('L',14,'He turned.','वो मुड़ गए।','ఆయన వెనక్కి తిరిగాడు.',None)],
'M6': [
 ('L',1,'Viśvāmitra had turned to go.','विश्वामित्र जाने को मुड़ चुके थे।','విశ్వామిత్రుడు వెళ్ళిపోవడానికి తిరిగాడు.',None),
 ('L',2,'Vasiṣṭha stood up.','वसिष्ठ खड़े हो गए।','వసిష్ఠుడు లేచి నిలబడ్డాడు.',None),
 ('P','pause',1.2),
 ('L',4,'He told the king: a man of this house keeps his word.','उन्होंने राजा को बताया — इस घर का आदमी वचन निभाता है।','రాజుకి చెప్పాడు — ఈ ఇంటి మనిషి మాట తప్పడు.',VS),
 ('P','pause',1.2),
 ('L',8,'Then he told him: the sage he refused was Rāma\'s protection.','फिर बताया — जिस ऋषि को वो मना कर रहे थे, वही राम की रक्षा थे।','తర్వాత చెప్పాడు — ఎవరిని కాదంటున్నాడో, ఆ ఋషే రాముడికి రక్ష.',VS),
 ('P','pause',1.2),
 ('L',15,'Dasharatha called for his son.','दशरथ ने बेटे को बुलाया।','దశరథుడు కొడుకుని పిలిచాడు.',None),
 ('P','two seconds',2.0),
 ('L',19,'And gave him.','और दे दिया।','ఇచ్చేశాడు.',None)],
'M7': [
 ('L',2,'Then they left.','फिर वो निकल पड़े।','ఆ తర్వాత బయలుదేరారు.',None),
 ('P','pause',1.2),
 ('L',9,'Viśvāmitra went first.','आगे विश्वामित्र।','ముందు విశ్వామిత్రుడు.',None),
 ('L',10,'Then Rāma.','फिर राम।','తర్వాత రాముడు.',None),
 ('L',11,'Then Lakṣmaṇa, following his brother.','फिर लक्ष्मण, भाई के पीछे-पीछे।','తర్వాత లక్ష్మణుడు, అన్నయ్య వెంటే.',None),
 ('P','the rest of the film is picture and sound — no narration',0)],
}


# What every narration unit asserts, and the evidence it rests on. The narrator may state
# SOURCE_FACT, attributed CHARACTER_SPEECH, and grounded INTERPRETATION. An ARTISTIC_BRIDGE
# may render a sourced action or carry no event at all; it may never assert an invented event.
# CHARACTER_SPEECH           speaker set; the narration itself carries the attribution.
# NARRATOR_PARAPHRASE:<who>  the narrator restates what a character said; <who> is the original speaker.
# SOURCE_FACT                independent narrative support — the text's narrator says it.
# INTERPRETATION / ARTISTIC_BRIDGE as before.
NP = lambda who: f'NARRATOR_PARAPHRASE:{who}'
CLASS = {
 'M1': [('SOURCE_INFERRED','Dutt XVIII — Daśaratha asks "the purpose of thy coming"; the arrival itself is narrated in sarga 17, not loaded'),
        ('CHARACTER_SPEECH','Dutt XVIII — Daśaratha asks'),
        (NP(D),'CLM-0001 — the promise is Daśaratha\'s own speech'),
        (NP(D),'CLM-0001 — the scope of his promise'),
        ('SOURCE_FACT','sequence: XVIII precedes XIX')],
 'M2': [('SOURCE_INFERRED','the audience is Dutt XIX; the seating is inferred'),
        (NP(D),'CLM-0001'),('CHARACTER_SPEECH','CLM-0009, 18.3; Dutt XIX "prove firm in promise"'),(NP(V),'CLM-0002'),(NP(V),'CLM-0003'),(NP(V),'CLM-0004 — onto the altar, 18.5'),
        (NP(V),'CLM-0005'),('SOURCE_FACT','18.6–8 — he is there, stating his need'),
        (NP(V),'CLM-0007, 18.17'),('INTERPRETATION','true by omission: 18.8 asks for Rāma, not an army'),
        (NP(V),'CLM-0006')],
 'M3': [('CHARACTER_SPEECH','CLM-0008; na saṃśayaḥ 18.10'),
        ('CHARACTER_SPEECH','CLM-0019, 18.16; Dutt XIX — the condition M6 pays off'),(NP(V),'CLM-0007, recalled from M2'),
        ('INTERPRETATION','the fear is SOURCE_FACT at 18.20 — CLM-0016 (Dutt: sorrow, apprehension); "not of Rāma, for him" is ours'),
        ('CHARACTER_SPEECH','CLM-0010'),('CHARACTER_SPEECH','CLM-0011'),(NP(D),'CLM-0012'),
        ('CHARACTER_SPEECH','CLM-0013'),('INTERPRETATION','summarises 19.3–11'),
        ('CHARACTER_SPEECH','CLM-0014'),('CHARACTER_SPEECH','CLM-0015')],
 'M4': [('CHARACTER_SPEECH','CLM-0020, 19.12–13'),('ARTISTIC_BRIDGE','"slowly" is ours'),
        ('CHARACTER_SPEECH','CLM-0031'),(NP(V),'CLM-0030'),(NP(V),'CLM-0030, CLM-0032'),
        ('ARTISTIC_BRIDGE','no event beyond the naming'),('CHARACTER_SPEECH','CLM-0034'),
        ('CHARACTER_SPEECH','CLM-0035, 19.23'),('CHARACTER_SPEECH','CLM-0035')],
 'M5': [('ARTISTIC_BRIDGE','our staging of his stillness'),('ARTISTIC_BRIDGE','the movement is ours; the anger it renders is CLM-0040, 20.1'),
        ('ARTISTIC_BRIDGE','opens the quoted run'),('CHARACTER_SPEECH','CLM-0041'),('CHARACTER_SPEECH','CLM-0041'),
        ('CHARACTER_SPEECH','CLM-0042'),('CHARACTER_SPEECH','CLM-0043'),('CHARACTER_SPEECH','CLM-0043'),
        ('ARTISTIC_BRIDGE','renders 20.3; the turning is ours')],
 'M6': [('ARTISTIC_BRIDGE','renders 20.3'),('ARTISTIC_BRIDGE','renders 20.5; standing is ours'),
        ('CHARACTER_SPEECH','CLM-0050'),('CHARACTER_SPEECH','CLM-0051'),
        ('SOURCE_FACT','21.1 — CLM-0056; Dutt XXII'),('SOURCE_FACT','CLM-0052, 21.3')],
 'M7': [('SOURCE_FACT','21.6 — the departure; no hour is given'),('SOURCE_FACT','CLM-0054'),
        ('SOURCE_FACT','CLM-0054'),('SOURCE_FACT','CLM-0053')],
}
