#!/usr/bin/env node
// install_stills - install externally authored stills as a film's frames.
//
// These were made elsewhere and reviewed by a human. The studio did not generate them,
// and the record must never imply it did: every one carries the provider, the source
// file name, the source hash, and the hash of the scaled frame actually used.
//
// Scaling: the sources are ~9:16 but not exactly (941x1672, and 941x1671 for one). They
// are scaled to COVER 1080x1920 with Lanczos and centre-cropped by the 1-2 pixel
// excess. Cover-and-crop, never pad: a pad would put a black edge in the frame, and
// never stretch: an anamorphic frame is a worse error than one lost pixel column.
import { read, treatment, ensureDir, assetsDir, ROOT } from '../lib/store.js';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const PROVIDER = 'Codex (OpenAI image generation)';
const srcDir = process.argv[2];
const filmId = process.argv[3] ?? 'M1';
const run = process.argv.includes('--run');
if (!srcDir) { console.error('\n  usage: node tools/install_stills.js <dir> [film] [--run]\n'); process.exit(2); }

const sha = (b) => createHash('sha256').update(b).digest('hex');
const probe = (f) => execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=width,height',
  '-of', 'csv=p=0:s=x', f], { encoding: 'utf8' }).trim().split('x').map(Number);

const t = treatment(filmId);
const files = readdirSync(srcDir).filter((f) => /\.(png|jpe?g)$/i.test(f));
const byShot = new Map();
for (const f of files) {
  const m = f.match(/(\d{2}-\d{2})/);
  if (m) byShot.set(m[1], join(srcDir, f));
}

console.log(`\nINSTALL STILLS ${filmId} - ${byShot.size} supplied, provider "${PROVIDER}"\n`);
const rows = [];
for (const s of t.shots) {
  const src = byShot.get(s.id);
  if (!src) continue;
  const [w, h] = probe(src);
  rows.push({ shot: s.id, src, w, h });
}
const generated = t.shots.filter((s) => s.source === 'generate').map((s) => s.id);
const kept = generated.filter((id) => !byShot.has(id));
console.log(`  ${rows.length} to install, ${kept.length} kept from earlier renders: ${kept.join(', ') || '(none)'}`);
for (const r of rows) {
  const exact = r.w === 1080 && r.h === 1920;
  console.log(`    ${r.shot}  ${r.w}x${r.h}${exact ? '' : '  -> cover-scale Lanczos, centre-crop to 1080x1920'}`);
}
if (!run) { console.log('\n  Nothing was written. Add --run.\n'); process.exit(0); }

const dir = ensureDir(`${assetsDir()}/stills/${filmId}`);
const recDir = ensureDir(`renders/${filmId}`);
for (const r of rows) {
  const srcBytes = readFileSync(r.src);
  const out = join(dir, `${r.shot}.png`);
  execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-i', r.src,
    '-vf', 'scale=1080:1920:force_original_aspect_ratio=increase:flags=lanczos,crop=1080:1920',
    '-frames:v', '1', '-y', out], { stdio: ['ignore', 'ignore', 'pipe'] });
  const outBytes = readFileSync(out);
  const [ow, oh] = probe(out);
  if (ow !== 1080 || oh !== 1920) { console.error(`  ${r.shot}: produced ${ow}x${oh}, not 1080x1920`); process.exit(1); }

  const local_path = `${assetsDir()}/stills/${filmId}/${r.shot}.png`;
  writeFileSync(join(recDir, `${r.shot}.json`), JSON.stringify({
    film: filmId, shot: r.shot,
    local_path, sha256: sha(outBytes), bytes: outBytes.length,
    authored_elsewhere: true,
    provider: PROVIDER,
    source_file: r.src.split('/').pop(),
    source_sha256: sha(srcBytes),
    source_size: `${r.w}x${r.h}`,
    scaled: {
      to: '1080x1920',
      how: 'cover-scaled with Lanczos, then centre-cropped by the excess. No pad, no stretch.',
      note: `${r.w}x${r.h} is ${(r.w / r.h).toFixed(4)} against the frame's ${(1080 / 1920).toFixed(4)}`,
    },
    approved_for_use_by: 'Venkat',
    reviewed: 'all 12 reviewed and approved for use, 2026-09-22',
    text_only: null,
    conditioned_on: null,
    note: 'Not generated by this studio. The prompt, the references and the seed are not the studio\'s to record.',
    at: new Date().toISOString(),
  }, null, 2) + '\n', 'utf8');
  console.log(`  ${r.shot}  ${r.w}x${r.h} -> 1080x1920  ${sha(outBytes).slice(0, 12)}  (src ${sha(srcBytes).slice(0, 12)})`);
}
console.log(`\n  ${rows.length} installed. ${kept.length} kept: ${kept.join(', ')}\n`);
